-- 코드를 입력하세요

    SELECT AU.AUTHOR_ID
         , AU.AUTHOR_NAME
         , BK.CATEGORY
         , SUM(BK.PRICE * BS.SALES) AS TOTAL_SALES
    FROM BOOK BK
    INNER JOIN AUTHOR AU ON BK.AUTHOR_ID = AU.AUTHOR_ID
    INNER JOIN BOOK_SALES BS ON BK.BOOK_ID = BS.BOOK_ID
    WHERE TO_CHAR(BS.SALES_DATE,'YYYY-MM') = '2022-01'
    GROUP BY AU.AUTHOR_ID, BK.CATEGORY, AU.AUTHOR_NAME
    ORDER BY AU.AUTHOR_ID, BK.CATEGORY DESC;
    